### PR TITLE
 Update BSP layer

### PR DESCRIPTION
**Pull request by RockSupport**
layers/meta-isg: Update BSP layer
    
    Changelog-entry: layers/meta-isg: Update BSP layer to Use rk u-boot to meet production requirements and to include kernel PMIC driver fix reboot issue

    Signed-off-by: <support@rockemb.com>

### CODE REVIEW

**Comment by RockSupport** [comment]
@acostach Is there something wrong with this PR?

**Comment by acostach** [comment]
HI @RockSupport , automated versioning fails and it looks like it's because of the commit message, can you please do a git commit --amend and replace your entire message with the one below? Please paste the exact message below. You can then do git push origin your_branch --force and the PR will be updated automatically:

```
layers/meta-isg: Update BSP layer to include u-boot fixes

Changelog-entry: layers/meta-isg: Update BSP layer to include u-boot fixes for reboot
Signed-off-by: Rocktech Support <support@rockemb.com>
```

**Comment by RockSupport** [comment]
@acostach  Thanks for your patience.
I have few experience about git and github,I use svn instead of git before,write source code by myself.
Git and github are very powerful,I'm learning to use them.
I think there are some rules about pull request

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
Hi @RockSupport, not a problem, the versioning check is now passed. You can view the full UUID along with other information about a specific device with `balena device <uuid>` and you can use both short and long UUID interchangeably. 

The full list of options for balena cli is available with:

```
balena --help
USAGE
$ balena [COMMAND] [OPTIONS]

PRIMARY COMMANDS
  login                                  login to balena
  push <applicationOrDevice>             start a build on the remote balenaCloud build servers, or a local mode device
  logs <device>                          show device logs
  ssh <applicationOrDevice> [service]    SSH into the host or application container of a device
  apps                                   list all applications
  app <nameOrSlug>                       display information about a single application
  devices                                list all devices
  --> device <uuid>                          show info about a single device
  tunnel <deviceOrApplication>           tunnel local ports to your balenaOS device
  preload <image>                        preload an app on a disk image (or Edison zip archive)
  build [source]                         build a project locally
  deploy <appName> [image]               deploy a single image or a multicontainer project to a balena application
  join [deviceIpOrHostname]              move a local device to an application on another balena server
  leave [deviceIpOrHostname]             remove a local device from its balena application
  scan                                   scan for balenaOS devices on your local network

...MORE run balena help --verbose to list additional commands.

GLOBAL OPTIONS
  --help, -h
  --debug

For further help or support, visit:
https://www.balena.io/docs/reference/balena-cli/#support-faq-and-troubleshooting
```

**Comment by RockSupport** [comment]
@acostach 
I can not get the full uuid 

**balena scan**
Scanning for local balenaOS devices... Reporting scan results

  host:      d1fcb8c.local
  address:   192.168.1.143
  osVariant: production

**balena device d1fcb8c**
BalenaDeviceNotFound: Device not found: d1fcb8c


**balena device d1fcb8c.local**
BalenaDeviceNotFound: Device not found: d1fcb8c.local

**Comment by acostach** [comment]
@RockSupport are you logged in (balena login) and is the device you are trying to access provisioned in your dashboard application, are you able to see it in the dashboard? If you are using the staging dashboard you will need to prefix you cli commands with BALENARC_BALENA_URL=balena-staging.com , eg: 
```
BALENARC_BALENA_URL=balena-staging.com balena login
BALENARC_BALENA_URL=balena-staging.com balena device <uuid>
```

**Review by acostach — APPROVED** [review]
lgtm, we'll need to check where the u-boot environment is stored because it should be stored in the u-boot binary and not in the emmc. will update this in a subsequent commit

**Comment by acostach** [comment]
@RockSupport which are the RS232 pins on the ISG 503, does it work with a 3.3V uart or what sort of uart interface should be used? Should it support UART 485, if yes on which pins and how can that be tested?

**Comment by acostach** [comment]
@RockSupport I'm trying to obtain u-boot logs, I've tried pins A0, B0, GND with RS232 adapter and am seeing no u-boot or kernel logs, can you please provide info on how to obtain u-boot console logs?

**Comment by acostach** [comment]
Also @RockSupport , perhaps you can look into this issue on your side @RockSupport if you have u-boot console access. In the hostOS (v2.85.2+rev4) please do the following:

1) ls -l /dev/disk/by-state -> active rootfs should be mmcblk1p2
2) hostapp-update -i acostach/isg:test1 # this is a build of v2.85.2+rev4
3) rm /mnt/sysroot/inactive/current/boot/init && reboot

Observe debug logs on uart, both u-boot and kernel. The device should reboot, then trigger a kernel panic because init was removed at step 3, and the panic should trigger a reboot. The next boot should be in the original root filesystem (mmcblk1p2, check with 1).

In u-boot you should also see the following log:
```
WARNING! BOOTLIMIT EXCEEDED. SWITCHING TO PREVIOUS ROOT;" 
WARNING! was: resin_root_part=3
```
as visible here:
https://github.com/balena-os/meta-balena/blob/master/meta-balena-common/recipes-bsp/u-boot/patches/env_resin.h#L151

I can't see what's happening without uart debug logs, all I see the ethernet LEDs turn on and off and suspect some command in u-boot may be failing and that's why the device doesn't boot back in the original rootfs.

**Comment by RockSupport** [comment]
@acostach The list is the pin mapping：
A0 BO  ----------   RS-485  ------ttyS0           
A2 B2  GND -----  RS-232 -------ttyWCH1      #uart 5
A1 B1 ------------RS-485  -------ttyWCH0     
These pins is used by customer applications,I use uart2m1 as debug port. If you want see the log of kernel and uboot,we have to   switch the debug port to uart 5 or  dismantled the device JP1 pin18-->UART2_TX_M1 pin22--->UART2_RX_M1 ,pin20--->GND

**Comment by RockSupport** [comment]
@acostach  "if test ${bootcount} -gt ${os_bc_lim}" have some problem
https://github.com/balena-os/meta-balena/blob/master/meta-balena-common/recipes-bsp/u-boot/patches/env_resin.h#L150
**printenv os_bc_lim bootcount**
_os_bc_lim=1
bootcount=0x3_
if bootcount=3 it will be fine

**Comment by acostach** [comment]
@RockSupport I see, so it's because setexpr saves the number as hex instead of decimal in this u-boot version and then comparison fails?

https://github.com/balena-os/meta-balena/blob/09ac68f9f6c3b5fc1de906b39bf6d147d11525fc/meta-balena-common/recipes-bsp/u-boot/patches/env_resin.h#L142
https://github.com/balena-os/meta-balena/blob/master/meta-balena-common/recipes-bsp/u-boot/patches/env_resin.h#L77

**Comment by RockSupport** [comment]
@acostach the cmd/test.c L132 
		_case OP_INT_GT:
			expr = simple_strtol(ap[0], NULL, 10) >
					simple_strtol(ap[2], NULL, 10);_
I think the third parm of simple_strtol should be 0 , if we want compare between decimal  and hex, but it give 10

**Comment by acostach** [comment]
@RockSupport it looks like the commit c0b4a82d396c44e9a8222946b6c5158a9c55a86b in u-boot-rockchip was causing the problem, I reverted it in https://github.com/balena-os/balena-isg/pull/9 and now the bootcount is stored in decimal in /mnt/boot/bootcount.env (instead of hex previously) and also rollback started working fine.

**Comment by acostach** [comment]
> @acostach The list is the pin mapping： A0 BO ---------- RS-485 ------ttyS0 A2 B2 GND ----- RS-232 -------ttyWCH1 #uart 5 A1 B1 ------------RS-485 -------ttyWCH0 These pins is used by customer applications,I use uart2m1 as debug port. If you want see the log of kernel and uboot,we have to switch the debug port to uart 5 or dismantled the device JP1 pin18-->UART2_TX_M1 pin22--->UART2_RX_M1 ,pin20--->GND

Thanks @RockSupport, can I power the board trough USBC, without the CAPE mounted, so that I can access JP1.18, JP1.20 and JP1.22 ?

**Comment by RockSupport** [comment]
@acostach I have sent a email

**Comment by acostach** [comment]
Thank you @RockSupport , I've received the image in the e-mail.

**Comment by acostach** [comment]
@RockSupport the image you contributed is now available in production at https://dashboard.balena-cloud.com

**Comment by RockSupport** [comment]
Thank you @acostach
We are preparing for mass production

**Pull request merged**
