### PR TITLE
bsp update

### PR DESCRIPTION
**Pull request by RockSupport**
fix reboot issue
Use rk u-boot to  meet production requirements

### CODE REVIEW

**Comment by RockSupport** [comment]
@acostach Could you verify these patch?

**Comment by acostach** [comment]
Thanks for the PR @RockSupport , can you please change the commit message for this one: https://github.com/balena-os/balena-isg/pull/5/commits/c796b50ef1535d151f73182211338a77949e0df0

to include changelog-entry and SOB? An example commit message would be:
```

layers/meta-isg: Update BSP layer to include u-boot fixes

Changelog-entry: layers/meta-isg: Update BSP layer to include u-boot fixes for reboot
Signed-off-by: <you@your-email-address.com>
```

Also, this commit needs to be dropped entirely from the PR: https://github.com/balena-os/balena-isg/pull/5/commits/6200bd7cfd620b95c11a87e754e741c2f7c616af because the functionality is provided by the OS. If you wish to make the uuid generation configurable, please open a PR in meta-balena: https://github.com/balena-os/meta-balena/pulls

**Comment by RockSupport** [comment]
@acostach   PR: 6200bd7  is not a universal feature , but a customization.
Our customer need generate a QR code based on the UUID,it is difficult to get a uuid on the production line

**Comment by acostach** [comment]
@RockSupport having this customizable is a good idea, perhaps the trough a single variable that gets set here in the device layer, but the core functionality of generating the uuid based on various inputs still needs to be included trough the meta-balena OS layer. Duplicating meta-balena sources in device layers should be avoided, so can you please open a PR in meta-balena for this specific feature?

**Comment by RockSupport** [comment]
@RockSupport Can we get the UUID  from a production version of BalenaOS in local network ?
Could you give some advices?

**Comment by acostach** [comment]
@RockSupport you can see the uuid from the App container with env | grep BALENA_DEVICE_UUID

Also, from another device you can use balena-cli, for instance:

```
~$ sudo balena scan
Scanning for local balenaOS devices... Reporting scan results
- 
  host:      5364e76.local
  address:   192.168.0.142
  osVariant: production
- 
  host:      eaab5dc.local
  address:   192.168.0.154
  osVariant: production
```

You can also have a look at pre-registering devices, which allows you to generate the UUID for each device and inject it into the image before flashing the device: https://www.balena.io/docs/learn/more/masterclasses/advanced-cli/#52-preregistering-a-device

**Comment by RockSupport** [comment]
@acostach 5364e76 is short of UUID ,can we get the full UUID?

**Pull request closed without merging**
