### PR TITLE
BSP:Change bsp layer

### PR DESCRIPTION
**Pull request by RockSupport**
use meta-rockchip instead of meta-isg

Changelog-entry: Change bsp layer
Signed-off-by: kun.zhang@rockemb.com

### CODE REVIEW

**Comment by RockSupport** [comment]
Could we create a new branch for this pr

**Comment by RockSupport** [comment]
@resin-jenkins Is there any thing wrong with this Pr?

**Comment by alexgg** [comment]
hey @RockSupport the PR looks fine, but it has conflicts that need to be resolved. Would you please fix the conflicts and re-ping either myself or @floion ? Thanks.

**Comment by RockSupport** [comment]
@alexgg Do I have to sync this project and Pr again?

**Comment by alexgg** [comment]
hi @RockSupport yes, the changes need to be rebased over balena-isg master branch, merge commits will not be accepted by the CI as a policy.

**Comment by RockSupport** [comment]
hi @alexgg Will this Pr deploy immediately after I commit to master branch. We want to test before it deployment

**Comment by alexgg** [comment]
hi @RockSupport once it merges it will deploy as a draft release (not available for API/SDK/dashboard updates) as this repository has no device types in our automation test rig. You can then manually install and test the draft release (we can provide instructions) and once you approve it balena will manually deploy a final release that will then be available in production.

**Comment by RockSupport** [comment]
Hi @alexgg ，thanks

**Comment by floion** [comment]
Can this PR be closed now?

**Pull request closed without merging**
